# Generated by Django 2.1.3 on 2018-11-22 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biaoti', models.CharField(default='', max_length=255)),
                ('neirong', models.TextField(blank=True, default='')),
                ('fabiao_riqi', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='post_images')),
                ('yuedu', models.PositiveIntegerField(default=0)),
                ('dianzan', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, default='', upload_to='post_files')),
            ],
        ),
        migrations.CreateModel(
            name='Lanmu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='artical',
            name='lanmu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shiju.Lanmu'),
        ),
    ]
