# Generated by Django 2.1.3 on 2018-11-23 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiju', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jigou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Suplanmu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='lanmu',
            name='jigou',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='shiju.Jigou'),
        ),
        migrations.AddField(
            model_name='lanmu',
            name='sup_lanmu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sub_lanmu', to='shiju.Suplanmu'),
            preserve_default=False,
        ),
    ]
