# Generated by Django 2.1.3 on 2018-11-23 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiju', '0002_auto_20181123_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigou',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lanmu',
            name='jigou',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='shiju.Jigou'),
        ),
        migrations.AlterField(
            model_name='suplanmu',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
