# Generated by Django 2.1.3 on 2018-11-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shiju', '0004_auto_20181123_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanmu',
            name='jigou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shiju.Jigou'),
        ),
        migrations.AlterField(
            model_name='lanmu',
            name='sup_lanmu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_lanmu', to='shiju.Suplanmu'),
        ),
    ]
