# Generated by Django 2.1.3 on 2018-11-25 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiju', '0006_suplanmu_jigou'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artical',
            options={'ordering': ['-fabiao_riqi']},
        ),
    ]
