# Generated by Django 2.1.3 on 2018-11-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiju', '0007_auto_20181125_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='huishou',
            field=models.BooleanField(default=False),
        ),
    ]
