# Generated by Django 2.1.3 on 2018-11-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiju', '0009_auto_20181127_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigou',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jigou',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
