# Generated by Django 2.1 on 2018-11-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiju', '0010_auto_20181127_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanmu',
            name='zhiding',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artical',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='artical',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
