# Generated by Django 2.1.3 on 2018-11-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiju', '0011_auto_20181129_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jigou',
            options={'ordering': ['-daihao']},
        ),
        migrations.AddField(
            model_name='jigou',
            name='daihao',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
