# Generated by Django 2.1.3 on 2018-11-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiju', '0012_auto_20181129_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jigou',
            options={'ordering': ['daihao']},
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
